Hivemind/Hivemind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jumia.urls')),
    path('', include('user.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hivemind/jumia/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *


app_name = 'jumia'

urlpatterns = [
    path('', items, name='items'),
    path('detail/<int:id>',detail, name= 'detail'),

]

Hivemind/user/urls.py
from django.urls import path 
from .views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm


app_name = 'user'

urlpatterns = [
    path('signup/', SignUp, name='signup'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='user/login.html'), name='login'),
    path('logout/', Logout_view , name='logout'),
    path('sell/', Sell, name='sell' ),
    path('details/', Sell_details, name='sell_details' ),
]

Hivemind/business/models.py
from django.db import models

# Create your models here.

Hivemind/jumia/models.py
from django.db import models
from django.contrib.auth.models import User



class Categories(models.Model):
    category_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='category_images/', blank=True, null=True)

    class Meta:
        ordering = ['category_name',]
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.category_name
    
class Product(models.Model):
    categories = models.ForeignKey(Categories, related_name='name',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null= True)
    
    def __str__(self):
        return self.name
        
class Type(models.Model):
    Category = models.ForeignKey(Product, related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length = 250)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits = 30, decimal_places=2)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    is_available = models.BooleanField(default=True)
    product_by = models.ForeignKey(User, related_name = 'items', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    

Hivemind/user/models.py
from django.db import models

# Create your models here.

Hivemind/user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from jumia.models import Product, Type, Categories

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SellForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
    
class design(forms.Select):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.attrs['class'] = ' form-select w-full py-4 px-6 rounded-xl'

class DetailForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = '__all__'

    Category = forms.ModelChoiceField(queryset=Categories.objects.all(), widget=design)

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'product description',
        'class': 'w-full py-4 px-6 rounded-xl'}))
    

Hivemind/business/views.py
from django.shortcuts import render

# Create your views here.

Hivemind/jumia/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404, redirect
from .models import Categories, Product, Type
from django.http import HttpResponse



def items(request):
    categories = Categories.objects.all()
    products = Product.objects.all()
    type = Type.objects.all()

    return render(request, 'jumia/item.html', {'categories':categories,
                                                'products': products,
                                                'type': type})
@login_required
def detail(request, id):
    item = get_object_or_404(Type, pk=id)
    related_items = Type.objects.filter(Category=item.Category).exclude(pk=id)

    return render(request, 'jumia/detail.html', {
        'item': item,
        'related_items': related_items
    })



                

Hivemind/user/views.py
from django.shortcuts import render,redirect
from .forms import SignUpForm, SellForm, DetailForm
from django.contrib.auth import logout

def SignUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignUpForm()

    return render(request, 'user/signup.html', {'form':form})


def Logout_view(request):
    logout(request)
    return redirect('/')

def Sell(request):
    if request.method == 'POST':
        form = SellForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/details/')
    else:
        form = SellForm()

    return render(request, 'user/sell.html', {'form':form})


def Sell_details(request):
    if request.method == 'POST':
        form = DetailForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            return redirect('/')
    else:
        form = DetailForm()

    return render(request, 'user/sell_details.html', {'form':form})

Hivemind/jumia/templates/jumia/detail.html
{% extends 'jumia/detail_layout.html'%}
{% block title%} {{item.name}} {% endblock %}
{% block content %}
<h1 class="text-center py-4 text-3xl font-bold">PRODUCT DETAILS</h1>
<div class="container-fluid py-5">
    <div class="row px-xl-5">
        <div class="col-lg-5 pb-5">
            <div id="product-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner border">
                    <div class="carousel-item active">
                        <img class="w-100 h-100" src="{{item.image.url}}" alt="Image">
                    </div>
                   
                    
                </div>
                <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                    <i class="fa fa-2x fa-angle-left text-dark"></i>
                </a>
                <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                    <i class="fa fa-2x fa-angle-right text-dark"></i>
                </a>
            </div>
        </div>
        <div class="col-lg-7 pb-5">
            <h3 class="font-weight-semi-bold">{{item.name}}</h3>
            <div class="d-flex mb-3">
                <div class="text-primary mr-2">
                    <small class="fas fa-star"></small>
                    <small class="fas fa-star"></small>
                    <small class="fas fa-star"></small>
                    <small class="fas fa-star-half-alt"></small>
                    <small class="far fa-star"></small>
                </div>
                <small class="pt-1">(50 Reviews)</small>
            </div>
            <h3 class="font-weight-semi-bold mb-4">shs. {{item.price}}</h3>
            <p class="mb-4">From the iconic checkerboard slip-on to the legendary Old Skool, Vans offers timeless styles for men, women, and kids.  Built with comfort and durability in mind, Vans are perfect for skating, everyday wear, or expressing your unique style.  Shop their wide variety of colors, patterns, and materials to find the perfect Vans for you.</p>
            <div class="d-flex align-items-center mb-4 pt-2">
                <div class="input-group quantity mr-3" style="width: 130px;">
                    <div class="input-group-btn">
                        <button class="btn btn-primary btn-minus" >
                        <i class="fa fa-minus"></i>
                        </button>
                    </div>
                    <input type="text" class="form-control bg-secondary text-center" value="1">
                    <div class="input-group-btn">
                        <button class="btn btn-primary btn-plus">
                            <i class="fa fa-plus"></i>
                        </button>
                    </div>
                </div>
                <button class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> Add To Cart</button>
            </div>
        </div>
    </div>
</div>
<h2 class="text-center py-4 text-5xl font-bold"> Related items</h2>
<div class="flex flex-wrap">
    {% for item in related_items %}
    <div class="w-full md:w-1/2 lg:w-1/3 xl:w-1/4 p-4">
      <div class="bg-white rounded-lg shadow-md">
       <a href="{% url 'jumia:detail' item.id %}">
        <div class="p-4">
          <img src="{{item.image.url}}" alt="Product 1" class="w-full h-auto rounded-md mb-4">
          <h2 class="text-lg font-semibold text-gray-800 mb-2">{{item.name}}</h2>
          <p class="text-sm text-gray-600">Price: sh.{{item.price}}</p>
        </div>
       </a>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Hivemind/jumia/templates/jumia/detail_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} | Hivemind</title>
    {% load static %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!-- Favicon -->
    <link href="/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="" class="text-decoration-none">
                    <h1 class="text-3xl font-semi-bold font-sans">HIVEMIND</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">0</span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid mb-5">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                        <div class="nav-item dropdown">
                            {% for c in cat %}
                            <a href="#" class="nav-link" data-toggle="dropdown">{{c.category_name}}<i class="fa fa-angle-down float-right mt-1"></i></a>
                            {% endfor %}
                        </div>
                    </div>   
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="index.html" class="nav-item nav-link active">Home</a>
                            
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu rounded-0 m-0">
                                    <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                    <a href="checkout.html" class="dropdown-item">Checkout</a>
                                    <a href="detail.html" class="dropdown-item">product details</a>
                                </div>
                            </div>
                            <a href="contact.html" class="nav-item nav-link">Contact</a>
                        </div>
                        {% if request.user.is_authenticated %}
                        <div class="flex space-x-3">
                            <p><svg class="w-6 inline-block mb-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                              </svg>
                              <strong>{{user.username}}</strong></p>
                        </div>
                        {% else %}
                            <div class="navbar-nav ml-auto py-0">
                                <a href="{% url 'user:login' %}" class="nav-item nav-link">Login</a>
                                <a href="{% url 'user:signup' %}" class="nav-item nav-link">Register</a>
                            </div>
                        {% endif %}
                    </div>
                </nav>
                <div id="header-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active" style="height: 410px;">
                            <img class="img-fluid" src="{%static 'img/SHOPPER.jpg' %}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Quality products</h3>
                                    <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item" style="height: 410px;">
                            <img class="img-fluid" src="/static/img/SHOP FRUIT.png" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order with us</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                                    <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-prev-icon mb-n2"></span>
                        </div>
                    </a>
                    <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-next-icon mb-n2"></span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">HIVEMIND</span></h1>
                </a>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>makerere university</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@hivemind.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+256</p>
            </div>
            <div class="col">About us
                <li><a href="" target="_blank">About_us</a></li>
                <li><a href="" target="_blank">Terms&condition</a></li>     
                <li><a href="" target="_blank">refund&return policy</a></li><br>
                   
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">hivemind</a>.
                    
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="{%static 'js/main.js'%}"></script>
</body>
</html>

Hivemind/jumia/templates/jumia/item.html
{% extends 'jumia/base.html' %}
{% block title%} products {% endblock %}

{% block content %}
<h2 class="text-center py-4 text-5xl font-bold"> Newest items</h2>
<div class="flex flex-wrap">
    {% for item in type %}
    <div class="w-full md:w-1/2 lg:w-1/3 xl:w-1/4 p-4">
      <div class="bg-white rounded-lg shadow-md">
       <a href="{% url 'jumia:detail' item.id %}">
        <div class="p-4">
          <img src="{{item.image.url}}" alt="Product 1" class="w-full h-auto rounded-md mb-4">
          <h2 class="text-lg font-semibold text-gray-800 mb-2">{{item.name}}</h2>
          <p class="text-sm text-gray-600">Price: sh.{{item.price}}</p>
        </div>
       </a>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Hivemind/user/templates/user/login.html
{% extends 'user/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300  rounded-xl">
    <h1 class="mb-6 text-4xl text-center">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <br>
       <div class="flex justify-between mb-3">
        <a href="#"><p class="font-semibold text-lg hover hover:text-red-500">Forgot password?</p></a>
        <a href="{% url 'user:signup' %}" class="font-semibold text-lg hover hover:text-red-500">Don't have an account</a>
       </div>
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Login</button>
    </form>
</div>
{% endblock %}

Hivemind/user/templates/user/logout.html
{% extends 'user/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Logged Out Successfully</h1>

    <a href=""><button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Login</button></a>
</div>
{% endblock %}

Hivemind/user/templates/user/sell.html
{% extends 'user/base.html' %}

{% block title %}Sell{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300  rounded-xl">
    <h1 class="mb-6 text-4xl text-center">Sell a product</h1>

    <form method="post" action=".">
        {% csrf_token %}
        {{form.as_p}}
        
        
        <a href="{% url 'user:sell_details' %}">
            <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Next</button>
        </a>
    </form>
</div>
{% endblock %}

Hivemind/user/templates/user/sell_details.html
{% extends 'user/base.html' %}

{% block title %}Sell{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-300  rounded-xl">
    <h1 class="mb-6 text-4xl text-center">Product details</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
       
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Sell</button>
    </form>
</div>
{% endblock %}